"""add delivery fields to orders

Revision ID: ac3e8ffa1bdc
Revises: 288455592e9b
Create Date: 2026-09-08 23:29:09.404894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac3e8ffa1bdc"
down_revision: str | Sequence[str] | None = "288455592e9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("delivery_latitude", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "orders",
        sa.Column(
            "delivery_longitude", sa.Numeric(precision=9, scale=6), nullable=True
        ),
    )
    op.add_column(
        "orders",
        sa.Column(
            "delivery_distance_km", sa.Numeric(precision=8, scale=2), nullable=True
        ),
    )
    op.add_column(
        "orders",
        sa.Column("delivery_fee", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.execute(
        """
        UPDATE orders
        SET
            delivery_latitude = 0,
            delivery_longitude = 0,
            delivery_distance_km = 0,
            delivery_fee = 0
        WHERE delivery_latitude IS NULL
        """
    )
    op.alter_column("orders", "delivery_latitude", nullable=False)
    op.alter_column("orders", "delivery_longitude", nullable=False)
    op.alter_column("orders", "delivery_distance_km", nullable=False)
    op.alter_column("orders", "delivery_fee", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "delivery_fee")
    op.drop_column("orders", "delivery_distance_km")
    op.drop_column("orders", "delivery_longitude")
    op.drop_column("orders", "delivery_latitude")
    # ### end Alembic commands ###
